### ISSUE TITLE
Build Failed: Java SE version 12. 

### ISSUE THREAD

**Issue by piyushbajaj0704** [isac322/OneDrive-SDK-java#19]
Build file '/Users/piyush.bajaj/Downloads/OneDrive-SDK-java-master/build.gradle' line: 63
A problem occurred evaluating root project 'onedrive-sdk-java'.
> Could not resolve all files for configuration ':compile'.
   > Could not find netty-transport-native-epoll-osx-x86_64.jar (io.netty:netty-transport-native-epoll:4.1.38.Final).
     Searched in the following locations:
         https://jcenter.bintray.com/io/netty/netty-transport-native-epoll/4.1.38.Final/netty-transport-native-epoll-4.1.38.Final-osx-x86_64.jar

So, only till JDK 9 is supported?

**Comment by isac322** [comment]
Thank you for telling me.
It seems to be because of Netty's dependency on OS rather than JDK. I will get a macOS environment and test it.

**Comment by isac322** [comment]
It's corrected. Please check.
