### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by cgivre** [isac322/OneDrive-SDK-java#31]
@isac322 Thanks for your great library.  Sorry to be a pest, but would it be possible for you to publish a new release?  I'm looking to add this to Apache Drill and it would be best if we had a new release.  Thanks!!

**Comment by isac322** [comment]
https://github.com/isac322/OneDrive-SDK-java/releases/tag/v0.10.2
0.10.2 released!

**Comment by cgivre** [comment]
@isac322 Thanks for doing the release, but something is broken in jitpack and it isn't building.  Would you mind taking a look?
